sudo: false
language: python
python:
  - 3.5
install:
  - pip install tox-travis
  - pip install coveralls
addons:
  apt:
    packages:
      - doxygen
script:
  - tox
after_success:
  - coveralls
notifications:
  email: false
